name: Automatic deployments from dev to staging
on:
  workflow_dispatch:

jobs:
  sync-staging-branch-with-dev:
    name: Syncs staging branch with dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'dev' # If blank, default: triggered branch
          destination_branch: 'staging' # If blank, default: master
          pr_title: 'chore: merge dev into staging' # Title of pull request
          pr_body: ':crown: *An automated PR*' # Full markdown support, requires pr_title to be set
          pr_reviewer: 'jc-sf' # Comma-separated list (no spaces)
          pr_assignee: 'jc-sf' # Comma-separated list (no spaces)
          pr_label: 'staging-release' # Comma-separated list (no spaces)
          pr_draft: false # Creates pull request as draft
          pr_allow_empty: false # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
      - name: output-has-changed-files
        run: echo ${{steps.open-pr.outputs.has_changed_files}}
